export const BRC_DATA_CATALOG_CATEGORY_KEY = {
  ACCESSION: "accession",
  ANALYZE_GENOME: "analyzeGenome",
  ANNOTATION_STATUS: "annotationStatus",
  ASSEMBLY_COUNT: "assemblyCount",
  ASSEMBLY_TAXONOMY_IDS: "assemblyTaxonomyIds",
  CHROMOSOMES: "chromosomes",
  COVERAGE: "coverage",
  GC_PERCENT: "gcPercent",
  IS_REF: "isRef",
  LENGTH: "length",
  LEVEL: "level",
  SCAFFOLD_COUNT: "scaffoldCount",
  SCAFFOLD_L50: "scaffoldL50",
  SCAFFOLD_N50: "scaffoldN50",
  TAXONOMIC_GROUP: "taxonomicGroup",
  TAXONOMIC_LEVEL_CLASS: "taxonomicLevelClass",
  TAXONOMIC_LEVEL_FAMILY: "taxonomicLevelFamily",
  TAXONOMIC_LEVEL_GENUS: "taxonomicLevelGenus",
  TAXONOMIC_LEVEL_KINGDOM: "taxonomicLevelKingdom",
  TAXONOMIC_LEVEL_ORDER: "taxonomicLevelOrder",
  TAXONOMIC_LEVEL_PHYLUM: "taxonomicLevelPhylum",
  TAXONOMIC_LEVEL_SPECIES: "taxonomicLevelSpecies",
  TAXONOMIC_LEVEL_STRAIN: "taxonomicLevelStrain",
  TAXONOMIC_LEVEL_SUPERKINGDOM: "taxonomicLevelSuperkingdom",
  TAXONOMY_ID: "ncbiTaxonomyId",
  UCSC_BROWSER_URL: "ucscBrowserUrl",
};

export const BRC_DATA_CATALOG_CATEGORY_LABEL = {
  ACCESSION: "Accession",
  ANALYZE_GENOME: "Action",
  ANNOTATION_STATUS: "Annotation Status",
  ASSEMBLY_COUNT: "Assemblies",
  ASSEMBLY_TAXONOMY_IDS: "Taxonomy ID",
  CHROMOSOMES: "Chromosomes",
  COVERAGE: "Coverage",
  GC_PERCENT: "GC%",
  IS_REF: "Is Ref",
  LENGTH: "Length",
  LEVEL: "Level",
  SCAFFOLD_COUNT: "Scaffolds",
  SCAFFOLD_L50: "Scaffold L50",
  SCAFFOLD_N50: "Scaffold N50",
  TAXONOMIC_GROUP: "Taxonomic Group",
  TAXONOMIC_LEVEL_CLASS: "Class",
  TAXONOMIC_LEVEL_FAMILY: "Family",
  TAXONOMIC_LEVEL_GENUS: "Genus",
  TAXONOMIC_LEVEL_KINGDOM: "Kingdom",
  TAXONOMIC_LEVEL_ORDER: "Order",
  TAXONOMIC_LEVEL_PHYLUM: "Phylum",
  TAXONOMIC_LEVEL_SPECIES: "Species",
  TAXONOMIC_LEVEL_STRAIN: "Strain",
  TAXONOMIC_LEVEL_SUPERKINGDOM: "Superkingdom",
  TAXONOMY_ID: "Taxonomy ID",
  UCSC_BROWSER_URL: "UCSC Browser",
};
