export const BRC_DATA_CATALOG_CATEGORY_KEY = {
  ACCESSION: "accession",
  ANALYZE_GENOME: "analyzeGenome",
  ANNOTATION_STATUS: "annotationStatus",
  ASSEMBLY_COUNT: "assemblyCount",
  CHROMOSOMES: "chromosomes",
  COVERAGE: "coverage",
  GC_PERCENT: "gcPercent",
  IS_REF: "isRef",
  LENGTH: "length",
  LEVEL: "level",
  SCAFFOLD_COUNT: "scaffoldCount",
  SCAFFOLD_L50: "scaffoldL50",
  SCAFFOLD_N50: "scaffoldN50",
  STRAIN: "strain",
  TAXON: "taxon",
  TAXONOMY_ID: "ncbiTaxonomyId",
  UCSC_BROWSER_URL: "ucscBrowserUrl",
};

export const BRC_DATA_CATALOG_CATEGORY_LABEL = {
  ACCESSION: "Accession",
  ANALYZE_GENOME: "Action",
  ANNOTATION_STATUS: "Annotation Status",
  ASSEMBLY_COUNT: "Assemblies",
  CHROMOSOMES: "Chromosomes",
  COVERAGE: "Coverage",
  GC_PERCENT: "GC%",
  IS_REF: "Is Reference",
  LENGTH: "Length",
  LEVEL: "Level",
  SCAFFOLD_COUNT: "Scaffolds",
  SCAFFOLD_L50: "Scaffold L50",
  SCAFFOLD_N50: "Scaffold N50",
  STRAIN: "Strain",
  TAXON: "Species",
  TAXONOMY_ID: "Taxonomy ID",
  UCSC_BROWSER_URL: "UCSC Browser",
};
