import { ANALYSIS_METHOD, WORKFLOW_ID } from "./entities";

export const WORKFLOW_IDS_BY_ANALYSIS_METHOD: Partial<
  Record<ANALYSIS_METHOD, WORKFLOW_ID>
> = {
  [ANALYSIS_METHOD.REGULATION]: WORKFLOW_ID.REGULATION,
};
