import { ANALYSIS_METHOD, WORKFLOW_ID } from "./entities";

export const WORKFLOW_IDS_BY_ANALYSIS_METHOD: Partial<
  Record<ANALYSIS_METHOD, WORKFLOW_ID>
> = {
  [ANALYSIS_METHOD.REGULATION]: WORKFLOW_ID.REGULATION,
  [ANALYSIS_METHOD.TRANSCRIPTOMICS]: WORKFLOW_ID.TRANSCRIPTOMICS,
  [ANALYSIS_METHOD.VARIANT_CALLING]: WORKFLOW_ID.VARIANT_CALLING,
};
