name: Update trusted repos

on:
  schedule:
    # At 10:00 on Sunday
    - cron: "0 10 * * 7"

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  update-catalog:
    if: github.repository == 'galaxyproject/brc-analytics'
    permissions:
      contents: write
      pull-requests: write
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-python@v5
        with:
          python-version: "3.12"
          architecture: "x64"
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install python dependencies
        run: pip install -r ./catalog/build/py/requirements.txt
      - name: Install npm dependencies
        run: npm ci
      - name: Run catalog script
        run: npm run build-files-from-ncbi
      - name: Get current date
        id: date
        run: echo "date=$(date +'%Y-%m-%d')" >> $GITHUB_OUTPUT
      - name: Create Pull Request
        uses: peter-evans/create-pull-request@v7
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          title: "chore: update data catalog ${{ steps.date.outputs.date }}"
          commit-message: "chore: update data catalog ${{ steps.date.outputs.date }}"
